apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-monitor
  labels:
    app: worker-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-monitor
  template:
    metadata:
      labels:
        app: worker-monitor
    spec:
      containers:
      - name: worker-monitor
        image: surajn581/worker_monitor:1.01
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"